"""Phase 5 — the ranked comparison report (judged deliverable).

GET /api/report assembles everything already in SQLite into the final artefact:
ranked itemised quotes in GBP + PKR, red flags annotated with their benchmark
evidence, negotiation savings (revised prices), non-quote outcomes documented,
and a plain-language recommendation. Every figure carries its call id and
logged_at timestamp; calls that were really dialed carry the ElevenLabs
conversation_id (the recording link). Nothing here is generated by an LLM —
the report is a deterministic view over what was actually said on the calls.
"""
from fastapi import APIRouter

from .calls import _consultancy_total, _quotes_for, effective_rows
from .config import get_vertical
from .db import get_conn

router = APIRouter()

_SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2}


def _red_flags_for(conn, call_id: int, rules: dict) -> list[dict]:
    rows = conn.execute(
        "SELECT rule_id, detail, flagged_at FROM red_flags WHERE call_id = ? ORDER BY id",
        (call_id,),
    ).fetchall()
    return [
        {
            "rule_id": r["rule_id"],
            "severity": rules[r["rule_id"]]["severity"],
            "description": rules[r["rule_id"]]["description"],
            "detail": r["detail"],
            "flagged_at": r["flagged_at"],
        }
        for r in rows
        if r["rule_id"] in rules
    ]


def _savings(quotes: list[dict]) -> float:
    """GBP moved by negotiation: every revision measured against what it replaced."""
    return sum(
        q["revised_from"] - q["amount"]
        for q in quotes
        if q["is_revised"] and q["revised_from"] is not None and q["revised_from"] > q["amount"]
    )


def _recommendation(ranked: list[dict], others: list[dict], sym: str, secondary: str) -> str:
    """Plain language, deterministic — every claim traceable to a ranked entry."""
    if not ranked:
        return ("No complete itemised quotes yet. "
                + (f"{len(others)} call(s) ended in callbacks or declines — see below."
                   if others else "Run calls from the board to fill this report."))
    top = ranked[0]
    parts = [
        f"Recommended: {top['consultancy_name']} — lowest total consultancy charges at "
        f"{sym}{top['consultancy_total']:,.0f} (≈ {secondary} {top['consultancy_total_secondary']:,.0f})"
        + (" with no red flags." if not top["red_flags"] else
           f", but note {len(top['red_flags'])} red flag(s) below.")
    ]
    dep = min(
        (
            {**d, "consultancy_name": c["consultancy_name"]}
            for c in ranked for d in c["deposits"]
        ),
        key=lambda d: d["amount"],
        default=None,
    )
    if dep:
        parts.append(
            f"Cheapest deposit route: {dep['university']} at {sym}{dep['amount']:,.0f} "
            f"(via {dep['consultancy_name']})."
        )
    total_saved = sum(c["savings"] for c in ranked)
    if total_saved > 0:
        parts.append(f"Negotiation moved prices by {sym}{total_saved:,.0f} across the calls.")
    for c in ranked:
        for f in c["red_flags"]:
            if f["severity"] == "high":
                parts.append(f"Caution ({c['consultancy_name']}): {f['detail']}.")
    return " ".join(parts)


@router.get("/api/report")
def report() -> dict:
    v = get_vertical()
    cur = v["currency"]
    rate = cur["gbp_to_pkr_rate"]
    rules = {r["id"]: r for r in v["red_flag_rules"]}

    ranked, others = [], []
    with get_conn() as conn:
        for call in conn.execute("SELECT * FROM calls ORDER BY id").fetchall():
            quotes = _quotes_for(conn, call["id"])
            rows = effective_rows(quotes)
            entry = {
                "call_id": call["id"],
                "consultancy_name": call["consultancy_name"],
                "persona_id": call["persona_id"],
                "conversation_id": call["conversation_id"],  # recording link when dialed
                "started_at": call["started_at"],
                "outcome": call["outcome"],
                "outcome_detail": call["outcome_detail"],
                "red_flags": _red_flags_for(conn, call["id"], rules),
            }
            if call["outcome"] == "quote" and rows:
                total = _consultancy_total(rows)
                entry.update({
                    "items": rows,  # each row keeps its logged_at (evidence timestamp)
                    "consultancy_total": total,
                    "consultancy_total_secondary": round(total * rate),
                    "deposits": [
                        {"university": q["university"], "amount": q["amount"]}
                        for q in rows if q["item"] == "deposit" and q["university"]
                    ],
                    "savings": _savings(quotes),
                })
                ranked.append(entry)
            else:
                others.append(entry)

    ranked.sort(key=lambda c: (
        min((_SEVERITY_ORDER[f["severity"]] for f in c["red_flags"]), default=3) == 0,
        c["consultancy_total"],
    ))
    for i, c in enumerate(ranked, start=1):
        c["rank"] = i

    return {
        "vertical": v["display_name"],
        "currency": {"symbol": cur["symbol"], "quote_currency": cur["quote_currency"],
                     "secondary": cur["report_currency_secondary"], "rate": rate,
                     "rate_note": cur.get("rate_note")},
        "ranked": ranked,
        "others": others,
        "recommendation": _recommendation(
            ranked, others, cur["symbol"], cur["report_currency_secondary"]),
    }
